Strogue.Aira.Web/Controllers/CultureController.cs
namespace Strogue.Aira.Web.Controllers;

public class CultureController : Controller
{
    [HttpPost]
    public IActionResult SetCulture(string culture, string returnUrl)
    {
        Response.Cookies.Append(
            CookieRequestCultureProvider.DefaultCookieName,
            CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
            new CookieOptions { Expires = DateTimeOffset.UtcNow.AddDays(30) }
        );
        return LocalRedirect(returnUrl);
    }
}

Strogue.Aira.Web/Views/Shared/_AiraMasterLayout.cshtml
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en"
      class="light-style layout-menu-fixed"
      data-theme="theme-default" data-assets-path='@((HttpContextAccessor.HttpContext?.Request.PathBase ?? "") + "/")'
      data-framework="aspnetcore-mvc"
      data-template="vertical-menu-aspnet-core-mvc-template-free">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    @{
        var title = ViewData["Title"] as string ?? "";
        var appName = TempData.Peek("appName") as string ?? "";
        var productPage = TempData.Peek("productPage") as string ?? "";
    }
    <title>@title | @appName</title>
    <meta name="description" content="" />

    <!-- Canonical SEO -->
    <link rel="canonical" href="@productPage">
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="~/img/favicon/favicon.ico" />

    <!-- Core Styles -->
    @await Html.PartialAsync("Sections/_Styles")

    <!-- Vendor Styles -->
    @await RenderSectionAsync("VendorStyles", required: false)

    <!-- Page Styles -->
    @await RenderSectionAsync("PageStyles", required: false)

    <!-- Include Scripts for customizer, helper, analytics, config -->
    @await Html.PartialAsync("Sections/_ScriptsIncludes")
</head>

<body>
    <!-- Layout Content -->
    @RenderBody()
    <!--/ Layout Content -->
    <!-- Core Scripts -->
    @await Html.PartialAsync("Sections/_Scripts")

    <!-- Vendor Scripts -->
    @await RenderSectionAsync("VendorScripts", required: false)


    <!-- Main JS-->
    <script src="~/js/main.js"></script>

    <!-- Page Scripts-->
    @await RenderSectionAsync("PageScripts", required: false)

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>

</html>

Strogue.Aira.Web/Views/Shared/_BlankLayout.cshtml
@{
    Layout = "_CommonMasterLayout";
}

@section VendorStyles {
    @await RenderSectionAsync("VendorStyles", required: false)
}

@section PageStyles {
    @await RenderSectionAsync("PageStyles", required: false)
}

@RenderBody()

@section VendorScripts {
    @await RenderSectionAsync("VendorScripts", required: false)
}

@section PageScripts {
    @await RenderSectionAsync("PageScripts", required: false)
}

Strogue.Aira.Web/Views/Shared/_CommonMasterLayout.cshtml
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en"
      class="light-style layout-menu-fixed"
      data-theme="theme-default" data-assets-path='@((HttpContextAccessor.HttpContext?.Request.PathBase ?? "") + "/")'
      data-framework="aspnetcore-mvc"
      data-template="vertical-menu-aspnet-core-mvc-template-free">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    @{
        var title = ViewData["title"] as string ?? "";
        var appName = TempData.Peek("appName") as string ?? "";
        var productPage = TempData.Peek("productPage") as string ?? "";
    }
    <title>@title | @appName </title>
    <meta name="description" content="" />

    <!-- Canonical SEO -->
    <link rel="canonical" href='@productPage'>
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="~/img/favicon/favicon.ico" />

    <!-- Core Styles -->
    @await Html.PartialAsync("Sections/_Styles")

    <!-- Vendor Styles -->
    @await RenderSectionAsync("VendorStyles", required: false)

    <!-- Page Styles -->
    @await RenderSectionAsync("PageStyles", required: false)

    <!-- Include Scripts for customizer, helper, analytics, config -->
    @await Html.PartialAsync("Sections/_ScriptsIncludes")
</head>

<body>
    <!-- Layout Content -->
    @RenderBody()
    <!--/ Layout Content -->
    <!-- Core Scripts -->
    @await Html.PartialAsync("Sections/_Scripts")

    <!-- Vendor Scripts -->
    @await RenderSectionAsync("VendorScripts", required: false)


    <!-- Main JS-->
    <script src='~/js/main.js'></script>

    <!-- Page Scripts-->
    @await RenderSectionAsync("PageScripts", required: false)

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>

</body>

</html>

Strogue.Aira.Web/Views/Shared/_CulturePartial.cshtml
@inject IOptions<RequestLocalizationOptions> LocalizationOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();

    var cultureItems = LocalizationOptions.Value.SupportedUICultures!
        .Select(c => new SelectListItem { Value = c.Name, Text = c.Name })
        .ToList();

    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}

<div>
    <form asp-controller="Culture" asp-action="SetCulture" asp-route-returnUrl="@returnUrl">
        <select name="culture" class="form-select"
                onchange="this.form.submit();"
                asp-for="@requestCulture!.RequestCulture.UICulture.Name"
                asp-items="cultureItems">
        </select>
    </form>
</div>

Strogue.Aira.Web/Views/Shared/_Layout.cshtml
@await Html.PartialAsync("Sections/_Variables")
@{
    TempData.Keep();
    Layout = "_AiraMasterLayout";

    ViewData["contentNavbar"] = true;

    @* Display elements *@
    ViewData["isNavbar"] = (ViewData["isNavbar"] ??= true);
    ViewData["isMenu"] = (ViewData["isMenu"] ??= true);
    ViewData["isFlex"] = (ViewData["isFlex"] ??= false);
    ViewData["isFooter"] = (ViewData["isFooter"] ??= true);


    @*HTML Classes *@
    ViewData["navbarDetached"] = (ViewData["navbarDetached"] ?? "navbar-detached");

    @*Content classes *@
    ViewData["container"] = (ViewData["container"] ?? "container-xxl");
    ViewData["containerNav"] = (ViewData["containerNav"] ?? "container-xxl");
}

@section VendorStyles {
    @await RenderSectionAsync("VendorStyles", required: false)
}

@section PageStyles {
    @await RenderSectionAsync("PageStyles", required: false)
}

@section VendorScripts {
    @await RenderSectionAsync("VendorScripts", required: false)
}

@section PageScripts {
    @await RenderSectionAsync("PageScripts", required: false)
}

@{
    var isMenu = ViewData["isMenu"] != null && Convert.ToBoolean(ViewData["isMenu"]);
}

<div class='layout-wrapper layout-content-navbar @(isMenu ? "" : "layout-without-menu")'>
    <div class="layout-container">

        @if (isMenu)
        {
            @await Html.PartialAsync("Sections/Menu/_VerticalMenu")
        }

        <!-- Layout page -->
        <div class="layout-page">
            <!-- Navbar -->
            @if (@ViewData["isNavbar"] != null && Convert.ToBoolean(@ViewData["isNavbar"]))
            {
                @await Html.PartialAsync("Sections/Navbar/_Navbar")
            }
            <!-- / Navbar -->
            <!-- Content wrapper -->
            <div class="content-wrapper">

                <!-- Content -->
                <div class='@ViewData["container"] @(Convert.ToBoolean(@ViewData["isFlex"]) ? "d-flex align-items-stretch flex-grow-1 p-0" : "flex-grow-1 container-p-y")'>
                    @RenderBody()
                </div>
                <!-- / Content -->
                <!-- Footer -->
                @if (@ViewData["isFooter"] != null && Convert.ToBoolean(@ViewData["isFooter"]))
                {
                    @await Html.PartialAsync("Sections/Footer/_Footer")
                }
                <!-- / Footer -->
                <div class="content-backdrop fade"></div>
            </div>
            <!--/ Content wrapper -->
        </div>
        <!-- / Layout page -->
    </div>

    <!-- Overlay -->
    @if (@ViewData["isMenu"] != null && Convert.ToBoolean(@ViewData["isMenu"]))
    {
        <div class="layout-overlay layout-menu-toggle"></div>
    }
    <!-- Drag Target Area To SlideIn Menu On Small Screens -->
    <div class="drag-target"></div>
</div>